#!/usr/bin/env bash

title="Title Text"
description="Description Thing"
counter=9
textfile=text.txt # line could be kept to appropriate lengths using `fmt' utility
image=ansi

right_column()
    {
        echo "$description"
        printf "%02d" "$counter" | figlet -f small
        # figlet-toilet -f future
        cat "$textfile"
    }

# example of color escape sequences, notice how you can stack them
echo -e "\e[44m Bash \e[44;30mSCRIPT\e[0;44m ${title}\e[0m"
paste "$image" <(right_column)
