#!/bin/bash
# Author: @veggietorta
# Update: 02.14.21
# System: Ubuntu 20.10
# Purpose: Install neovim and/or supporting neovim items


echo $el_day_time ": Neovim file sourced" >> $el_log


menu_neovim()
{
    echo $el_day_time ": Entered menu_neovim function" >> $el_log

    clear

    # Promp user for input
    echo "Please select action:\n"
    echo "  1. Install Neovim"
    echo "  2. Install Plugin manager"
    echo "  3. Install custom .vimrc "
    echo "  4. Install custom font\n"
    echo "  r. Return to Main Menu"

    read user_input_neovim


    # Check if neovim is installed,
    #   if not, install neovim and vim.
    #   if installed, inform user and return user to top of menu_neovim
    if [ $user_input_neovim = "1" ];
    then

        # log
        echo $el_day_time ": Input received as 1, Intall Neovim" >> $el_log

        if [ -x "$(command -v nvim)" ];
        then
            # log
            echo $el_day_time ": Found neovim on system, send back to menu_neovim" >> $el_log
            echo "nvim already installed"
            sleep 2
            menu_neovim

        else
            # log
            echo $el_day_time ": Neovim not found on system, move forward with install" >> $el_log
            sudo apt install neovim vim -y
            menu_neovim
        fi

    # Install plugin manager
    elif [ $user_input_neovim = "2" ];
        then
            # log
            echo $el_day_time ": Input received as 2, Install Plugin Manager" >> $el_log

            # Plugin manager https://github.com/junegunn/vim-plug
            curl -fLo ~/.var/app/io.neovim.nvim/data/nvim/site/autoload/plug.vim https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

    # Custom .vimrc
    elif [ $user_input_neovim = "3" ];
        then
            rm $HOME/.vimrc
            ln -s $HOME/dotfiles/config/vim/.vimrc $HOME/
            # log it
            echo "Symbolic link to custom .vimrc establish"
            menu_neovim

    # Custom font
    elif [ $user_input_neovim = "4" ];
        then
            # Create directory for fonts and direct errors log.
            mkdir $HOME/.local/share/fonts > log 2>1&

            # Copy font from dotfiles to newly created directory
            cp $HOME/dotfiles/configs/font/Hack_Regular_Nerd_Font_Mono.ttf $HOME/.local/share/fonts/

            # Clear and regenerate font cache, requires fontconfig
            #fc-cache -f -v

            echo "Font 'Hack Regular Nerd Font Complete Mono' has been installed"
            # log it
            sleep 4
            menu_neovim


    # Return to main menu
    elif [ $user_input_neovim = 'r' ];
        then
            menu_ask_user


        else
            menu_neovim
    fi

}

