#!/bin/bash
# Author: @veggietorta
# Update: 02.14.21
# Purpose: Install zsh, Oh-my-zsh and any other supporting items


# Log entrance into 'zsh_install'
echo $el_day_time ": Zsh file sourced" >> $el_log


menu_zsh()
{

    echo $el_day_time ": Entered menu_zsh function"

    clear

    # Promp for action
    echo "Would you like to:\n"
    echo "1. Install zsh & oh-my-zsh"
    echo "2. Symbolic-link custom .zshrc"
    echo "3. Return to main menu"

    read zsh_user_input

    if [ $zsh_user_input = "1" ];
    then
        # Log input received as '1'
        echo $el_day_time ": User input received as 'Install zsh & oh-my-zsh'" >> $el_log

        # Remove any existing .zshrc file in $HOME directory and redirects output "2>&1", should .zshrc file doesn't exist
        # Install ZSH and '-y' approves any prompts
        # Install Oh-my-Zsh
        # Write to log
        # Send bach to ask_user
        rm $HOME/.zshrc > log 2>&1
        sudo apt install zsh -y
        clear
        sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
        menu_ask_user

    elif [ $zsh_user_input = "2" ];
    then
        # Log input received as '2'
        echo $el_day_time ": User input received as 'Symbolic-link custom .zshrc" >> $el_log

        # Remove any lingering .zshrc file and redirects output if a .zshrc file does not exist
        # Establish symbolic link
        # Sends user to main menu
        rm $HOME/.zshrc > log 2>&1
        ln -s $HOME/dotfiles/configs/zsh/ubuntu/.zshrc $HOME/
        clear
        menu_ask_user

    elif [ $zsh_user_input = "3" ];
    then
        # Log input receivd as '3'
        echo $el_day_time ": Input received as '3', return to main menu" >> $el_log

        # Return to menu
        clear
        menu_ask_user

    else #### review need for this else statement
        # Send back to menu
        clear
        menu_ask_user
    fi
}

