FROM alpine

# Author: @veggietorta
MAINTAINER @veggietorta

# Foundation apps
RUN apk add zsh && \
apk add git && \
apk add python3 && \
apk add neovim

# setup working directory
#ADD ~/Downloads /Downloads
#WORKDIR /Downloads

# expose port
EXPOSE 8080

# start zsh
CMD ["zsh"]
